language: csharp
solution: quizrt-social-server
notifications:
  email:
    on_success: always
    on_failure: always
  slack: cgiwave6:h9BQb1Y4KA4QNTysVx79hgt0
mono: none
dotnet: 2.1
script:
  - dotnet restore
  - dotnet test QuizRTSocial.Tests
after_success:
  - /bin/bash ./deploy.sh